### ISSUE TITLE
Test Failure: Close.io API should throw a verbose error

### ISSUE THREAD

**Issue by cpb** [closeio/closeio-node#11]
Hello,

Is this an expected test result?

```
  Close.io API
    ✓ should create, read, updated, delete and search for leads. (741ms)
    1) should throw a verbose error
    ✓ should create, read, update, delete lead statuses (550ms)
    ✓ should create, read, update, delete opportunity statuses (509ms)


  3 passing (4s)
  1 failing

  1) Close.io API should throw a verbose error:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

Or should there be an assertion that captures that time out error? What error are you expecting? Is this typical response time for the close.io service?

**Comment by philfreo** [comment]
I don't know what's going on with the codebase/test, however the Close.io API should be responding in under 2s for sure, so this likely seems like a node code issue.

**Comment by cpb** [comment]
Is there some kind of rich / "verbose" error that I am _not_ seeing? Could
I wrap this example in a try catch and make an assertion on the presence of
an error? Is this the error message we expect ? :-)

**Comment by philfreo** [comment]
I'm not sure... to be honest this is a pretty unsupported (or community supported) API wrapper so you might be better off simply doing basic HTTP requests to our REST API (developer.close.io) if it's giving you a ton of trouble. Improvements/pull requests welcome though if you do want to dive into the code and provide improvements here.

**Comment by cpb** [comment]
To be honest, I have barely looked at the code. I am just reporting on my
first impressions without much reading or analysis of what is here.

I hear you clearly though: this is community supported.

Does close.io have any precedent for inviting community members as
contributors?

Do you have any metrics for how many active api consumers are using this
code?

Cheers!

**Comment by pcothenet** [comment]
Fixed that one.
