### ISSUE TITLE
Maintainer needed

### ISSUE THREAD

**Issue by philfreo** [closeio/closeio-node#13]
Close.io isn't actively maintaining this unofficial node API client. If there's a Close.io customer who's been actively using it and would like to take over the npm repo, etc., please let us know.

**Comment by pcothenet** [comment]
Hey @philfreo, we're using this @MadKudu for our close.io integration. Currently depending on the unmerged pull request in the repo. Can't promise much but happy to take it over.

**Comment by philfreo** [comment]
Great. @nickpersico vouched for you. I've added you as a collaborator on this repo. Once this repo is in a place you're happy with let me know and I can also add you as a collaborator on the npm package.

**Comment by pcothenet** [comment]
Hi @philfreo, started making a few changes, would love to be able to publish to npm if you can let me do that :)

**Comment by philfreo** [comment]
Hey @pcothenet cool, thanks! I've added you as a publisher on npm.
