### ISSUE TITLE
Dependencies Vulnerabilities detected

### ISSUE THREAD

**Issue by arnaudbesnier** [closeio/closeio-node#16]
Running `nsp check --output summary`

You'll have 2 dependencies vulnerabilities detected:
```
close.io@0.0.7 > request@2.69.0 > tough-cookie@2.2.2
```

https://nodesecurity.io/advisories/130
https://nodesecurity.io/advisories/525

**Comment by taylorbrooks** [comment]
Fixed with the #18 PR.
