### ISSUE TITLE
Are new releases being published to the NPM registry?

### ISSUE THREAD

**Issue by chasingSublimity** [closeio/closeio-node#23]
Hiya!

I see that this repo is still active, but the registry page on NPM says that there has not been a deploy for about a year. Are there any plans to publish the current version of this project?

Thanks!

- Blake

**Comment by cypris75** [comment]
+1 

Asked Close.io support about it. No result yet.

**Comment by taylorbrooks** [comment]
Yikes! I missed this somewhow. Lemme push this out to NPM.

**Comment by philfreo** [comment]
Thanks Taylor!

**Comment by taylorbrooks** [comment]
Published!

**Comment by chasingSublimity** [comment]
Thanks friends! 🎊
